# Generated by Django 3.2.5 on 2021-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
    ]
